'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ObtenerMedia
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ObtenerMedia.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ObtenerMedia", ReplyAction:="http://tempuri.org/IService1/ObtenerMediaResponse")>  _
        Function ObtenerMedia(ByVal Asignatura As String) As Single
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/ObtenerMedia", ReplyAction:="http://tempuri.org/IService1/ObtenerMediaResponse")>  _
        Function ObtenerMediaAsync(ByVal Asignatura As String) As System.Threading.Tasks.Task(Of Single)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ObtenerMedia.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ObtenerMedia.IService1)
        Implements ObtenerMedia.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerMedia(ByVal Asignatura As String) As Single Implements ObtenerMedia.IService1.ObtenerMedia
            Return MyBase.Channel.ObtenerMedia(Asignatura)
        End Function
        
        Public Function ObtenerMediaAsync(ByVal Asignatura As String) As System.Threading.Tasks.Task(Of Single) Implements ObtenerMedia.IService1.ObtenerMediaAsync
            Return MyBase.Channel.ObtenerMediaAsync(Asignatura)
        End Function
    End Class
End Namespace
